### ISSUE TITLE
IPFS on 0-stor storage service

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/qss-ipfs-pinningserver#3]
We want to build a pinning service integrated with the Threefold Grid

## required reading
[IPFS concepts](https://docs.ipfs.tech/concepts/)
[Pinning](https://docs.ipfs.tech/how-to/pin-files/) 

## Pinning services
[Pinning services](https://ipfs.github.io/pinning-services-api-spec/)

The idea is quite simple 

### Pin object
- CID: content based id (hash)
- name: optional filename to identify the hash in the future
- origins: original peers having the pinned file (used to speed up the retrieval of the parts)
- meta: optional meta (can also be used for data filteration)

### PinStatus
- requestid: pinning request id, used for updates and deletions
- status: `queued`, `pinning`, `pinned`, `failed`
- delegates: the backend ipfs nodes the pinning service working against
- created: creation time? 
- info: vendor specific data (DAG size, raw size, pinned until if we work with time based pinning, .. etc)

### Pinning Lifecycle

![pinning](https://bafybeideck2fchyxna4wqwc2mo67yriokehw3yujboc5redjdaajrk2fjq.ipfs.dweb.link/lifecycle.png)

### example implementations
- [martianspins](https://github.com/sirodoht/martianpins)
- [rails example](https://github.com/ipfs-shipyard/rb-pinning-service-api)
 

### auth
Any auth mechanism will do, probably jwt is the bestin that case 

### Functional requirements
As the pinning service provider

- I should be able to provision the pinning solution and be to manage it as admin, in a simple way possibly through the playground or terraform
- The system needs to work with qsfs in the backend, so I'd be specifying number of ipfs nodes and all of them should be sharing the qsfs in backend
- The user needs to be paying for the storage and the bandwidth they're reserving
- I can have the backend qsfs scaled out, e.g system was using 1TB disks, and now want it to use 20TB, should be doable safely without risking the data.

As a user
- onboarding to the pinning service should be as easy as possible
- easy way to get the API token
- transparent billing 
- it needs to [work with the existing toolings of ipfs](https://docs.ipfs.tech/how-to/work-with-pinning-services/#use-an-existing-pinning-service)

### Non-functional requirements
- Use the go programming language
  - native support for libp2p and ipfs libraries
  - easy to do api servers with
  - single binary
  - already multiple people in the team can work with it

- Auth mechanism
  - JWT

- Frontend choice
  - Vue

 

### Considerations
- Request ID, which is generated when asking the server to pin an object, is tied to the lifetime of the pinned object. Specifically, it can be used to check the pin status of an object, and later on it can be used to delete the pin itself.
- The same object can be pinned multiple times. Each pin is managed by the corresponding request ID. As such, request ID's are forced to be unique.
- Bandwidth? all of the incoming traffic for the uploads will go through the pinning service, and then that pinning service will pin it to the backend ipfs nodes, the pinning service VM will be subject for high inbound/outbound traffic for files uploads and distribution to the backend services. solution could be running multiple instances of the pinning services on different farms
- Storage? running the some of the ipfs nodes on the same farm has the advantage of sharing the space which will cost less for the pinning to these backend ipfs nodes
- Gateways? the pinning service can't depend on a single farmer gateway, solution needs to be deployed with multiple gateway contracts, could we depend on using the public gateways of ipfs e.g ipfs.io?
- ZStor/0-dbfs: there is no linkage between content hashes and zstor, it can be done with one more level of indirection, e.g have a symlink that has the actual filename, or on the database of the pinning service api we maintain the `filename -> CID` and we store with the CID in 0-dbfs  

 ## Payment

The payment process should be in line with what we currently have, i.e. it should be done over the chain. However, since this is a service on top, rather than an actual grid integrated entity, we should develop a payment scheme which is sufficiently generic so that it can be used by other systems. This could look something like this: a fixed (repeated?) cost, together with periodic reporting of some cost (or some metric which gets converted to some cost on chain) by the service. Since we are dealing with possible third party services, the contract should also specify an upper bound on the variable payment part over some unit of time (e.g. max 1TFT / hour), to avoid abuse by malicious entities. Lastly, a small field with some variable data could be added to communicate something from the client to the service.

## Getting an access token

Pin services are authenticated via an access token. This is problematic since we want all setup to go though the chain, which means data there is public. As such, the service can't generate an access token and return that. The options are to have the service encrypt something using a shared key, which requires previous key exchange, or to have the client send something to the server which allows it to prove ownership of an access key. To do this, the client can:
1. generate an access key with some constraints.
2. hash the access key with a known hashing algorithm (e.g. blake2b-64)
3. include this hash in the contract on chain

the service can then read the hashed secret. If a client does an authenticated api request, it can check the access token, hash it, and verify that this is a known hash. This way the service has the access keys without direct communication with the client.

## Object metadata

0-stor already has some metadata about the files (objects) it stores. I suggest this is expanded to add a field which allows for arbitrary bytes to be included, which would be a client inserted object, which can then be the metadata about the object in a specific format.

## Mapping of object ID to object

Currently 0-stor uses a hash of the path as key for an object, however it should be trivial to allow user defined keys. This eliminates the need for a mapping of the objects.

**Comment by sameh-farouk** [comment]
let's clarify these requirements

> I can have the backend qsfs scaled out, e.g system was using 1TB disks, and now want it to use 20TB, should be doable safely without risking the data.

I believe zos atm doesn't support this kind of workload update. but I think we can deploy more 0-dbs, then 0-stor can expand the data to these new 0-dbs. no?

> The same object can be pinned multiple times. Each pin is managed by the corresponding request ID. As such, request ID's are forced to be unique.

if I understand this correctly, a request to remove the pin, for an object referenced by multiple requests IDs, would just remove the request from the DB and leave the object pinned as long as there are other requests that still reference the underlying object. am I right?

these points below need more clarification/details, what needs to be done exactly from the side of the pinning service:

> ZStor/0-dbfs: there is no linkage between content hashes and zstor, it can be done with one more level of indirection, e.g have a symlink that has the actual filename, or on the database of the pinning service api we maintain the filename -> CID and we store with the CID in 0-dbfs

> Getting an access token

> Currently 0-stor uses a hash of the path as key for an object, however it should be trivial to allow user defined keys. This eliminates the need for a mapping of the objects.

**Comment by xmonader** [comment]
@LeeSmet 

1- How can the access token be revoked by the user/service?
2- If it's a recurring cost, what happens if the pinning service is removed for any reason, will the billing keep happening without any protection for the user?

**Comment by sameh-farouk** [comment]
I still analyze the requirements per today's short call with @xmonader and I think we don't need to maintain a set of IPFS nodes for the pinning service. QSFS should be enough to handle the distribution of the data on multiple nodes, allowing redundancy and data resiliency.

Implementation-wise, it is enough for the pining service host to be also an IPFS node. the pinning service will communicate locally to the IPFS daemon to pin the data locally (if we want to keep it simple. stupid).

For having a set of remote IPFS nodes, we will have to deal with the increasing complexity such:
- Deploy and configure multi-ipfs node cluster (https://ipfscluster.io/documentation/deployment/), which peers communicate in a private manner and share the same cluster secret, have known public addresses for other cluster peers, and expose extra API to allow maintaining a global pinset. the pinning service host will run a cluster service too.
- Sharing the same qsfs/0-dbs backends/storage efficiently between cluster peers would be troublesome, if possible.

**Comment by LeeSmet** [comment]
> 1- How can the access token be revoked by the user/service?

That depends on how the access token is acquired. If it is passed from the client to the service on chain, it would require the contract to be invalidated. If there is an API/UI on the service to drive the creation of claims (which might be the best idea, and is what other systems already use), then access token management is simply part of the solution.

2- If it's a recurring cost, what happens if the pinning service is removed for any reason, will the billing keep happening without any protection for the user?

The recurring cost should only be billed if the service set the adaptive cost in the previous hour, thus implicitly showing it is live

**Comment by sameh-farouk** [comment]
Here is an Initial implementation [PR](https://github.com/threefoldtech/tf-pinning-service/pull/2)

https://github.com/threefoldtech/tf-pinning-service/tree/development_implementing_endpoints

Creating accounts and Auth is blocked on the blockchain part for now.
so I used a mock to continue with development.

**Comment by sameh-farouk** [comment]
I created sub issues from this story:
- [x] TF pinning service should work with the existing tooling of IPFS #5
- [ ] The IPFS storage layer needs to work with QSFS in the backend #6
- [ ] The user needs to be paying for the storage and the bandwidth they're reserving #7
- [ ] Implement admin endpoints to manage the service #8
- [ ] Implement Vue Front End for sign up #9
- [ ] I should be able to provision the pinning solution through the playground or terraform #10
- [ ] Authentication [signup/ generate access token/ revoke access token/ cancel contract] #12

**Comment by sameh-farouk** [comment]
**Update:**

@LeeSmet stated that there are some limitations in using 0-db-fs in a multi-node cluster

> qsfs (specifically 0-db-fs on top of 0-stor) is not multi-write (and currently not even multi-read), so you'll need to stick in single node mode if you want to use that. The main benefit here would be that qsfs provides "cheap" data redundancy if one of the storage backends fails

@xmonader suggested verifying the usage of qsfs minus 0-db-fs to overcome these limitations.

**Comment by despiegk** [comment]
the story owner has nothing to do with who executes the story, 
story owner needs to be selected can be sameh but then we expect better communication & deadline management to the other stakeholders
